<?php
session_start();

$configPath = __DIR__ . '/includes/config.php';
$schemaPath = __DIR__ . '/sql/schema.sql';
$errors = [];
$success = false;

if (empty($_SESSION['install_csrf'])) {
    $_SESSION['install_csrf'] = bin2hex(random_bytes(32));
}

function e($value) {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function quote_mysql_identifier($value) {
    return '`' . str_replace('`', '``', $value) . '`';
}

$form = [
    'db_host' => 'localhost',
    'db_name' => 'pernhome',
    'db_user' => 'pernhome',
    'site_name' => 'LANtern',
    'admin_username' => 'admin',
    'turnstile_site_key' => '',
    'turnstile_secret_key' => ''
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !is_file($configPath)) {
    if (!hash_equals($_SESSION['install_csrf'], $_POST['csrf'] ?? '')) {
        $errors[] = 'The installation form expired. Please try again.';
    }

    foreach ($form as $key => $value) {
        $form[$key] = trim($_POST[$key] ?? $value);
    }

    $dbPassword = $_POST['db_password'] ?? '';
    $adminPassword = $_POST['admin_password'] ?? '';
    $adminPasswordConfirm = $_POST['admin_password_confirm'] ?? '';

    if ($form['db_host'] === '' || $form['db_name'] === '' || $form['db_user'] === '') {
        $errors[] = 'Database host, name, and user are required.';
    }

    if (!preg_match('/^[A-Za-z0-9_]+$/', $form['db_name'])) {
        $errors[] = 'Database name may contain only letters, numbers, and underscores.';
    }

    if ($form['site_name'] === '' || $form['admin_username'] === '') {
        $errors[] = 'Site name and admin username are required.';
    }

    if (!preg_match('/^[A-Za-z0-9_.-]{1,50}$/', $form['admin_username'])) {
        $errors[] = 'Admin username may contain only letters, numbers, dots, underscores, and hyphens.';
    }

    if (strlen($adminPassword) < 12) {
        $errors[] = 'The admin password must be at least 12 characters long.';
    } elseif ($adminPassword !== $adminPasswordConfirm) {
        $errors[] = 'The admin passwords do not match.';
    }

    if (!$errors) {
        try {
            $pdoOptions = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
            ];

            $databaseDsn = 'mysql:host=' . $form['db_host'] . ';dbname=' . $form['db_name'] . ';charset=utf8mb4';

            try {
                $pdo = new PDO($databaseDsn, $form['db_user'], $dbPassword, $pdoOptions);
            } catch (PDOException $databaseException) {
                $serverPdo = new PDO(
                    'mysql:host=' . $form['db_host'] . ';charset=utf8mb4',
                    $form['db_user'],
                    $dbPassword,
                    $pdoOptions
                );

                $serverPdo->exec(
                    'CREATE DATABASE IF NOT EXISTS ' . quote_mysql_identifier($form['db_name']) .
                    ' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
                );

                $pdo = new PDO($databaseDsn, $form['db_user'], $dbPassword, $pdoOptions);
            }

            $schema = file_get_contents($schemaPath);
            if ($schema === false) {
                throw new RuntimeException('The database schema could not be read.');
            }

            $statements = preg_split('/;\s*(?:\R|$)/', $schema);
            foreach ($statements as $statement) {
                $statement = trim($statement);
                if ($statement !== '') {
                    $pdo->exec($statement);
                }
            }

            $settingInsert = $pdo->prepare(
                'INSERT INTO settings (setting_key, setting_value) VALUES (?, ?) '
                . 'ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)'
            );
            $settingInsert->execute(['site_name', $form['site_name']]);
            $settingInsert->execute(['turnstile_site_key', $form['turnstile_site_key']]);
            $settingInsert->execute(['turnstile_secret_key', $form['turnstile_secret_key']]);

            $userCheck = $pdo->prepare('SELECT COUNT(*) FROM users WHERE username = ?');
            $userCheck->execute([$form['admin_username']]);
            if ((int)$userCheck->fetchColumn() > 0) {
                throw new RuntimeException('That admin username already exists.');
            }

            $userInsert = $pdo->prepare(
                'INSERT INTO users (username, password_hash, role) VALUES (?, ?, \'admin\')'
            );
            $userInsert->execute([
                $form['admin_username'],
                password_hash($adminPassword, PASSWORD_DEFAULT)
            ]);

            $config = "<?php\n\n";
            $config .= "// Generated by install.php. Keep this file outside source control.\n";
            $config .= 'define(\'DB_HOST\', ' . var_export($form['db_host'], true) . ");\n";
            $config .= 'define(\'DB_NAME\', ' . var_export($form['db_name'], true) . ");\n";
            $config .= 'define(\'DB_USER\', ' . var_export($form['db_user'], true) . ");\n";
            $config .= 'define(\'DB_PASS\', ' . var_export($dbPassword, true) . ");\n\n";

            $temporaryConfig = $configPath . '.tmp-' . bin2hex(random_bytes(8));
            if (file_put_contents($temporaryConfig, $config, LOCK_EX) === false ||
                !rename($temporaryConfig, $configPath)) {
                @unlink($temporaryConfig);
                throw new RuntimeException('The configuration file could not be written.');
            }

            $success = true;
        } catch (Throwable $exception) {
            $errors[] = $exception->getMessage();
        }
    }
}

$installed = is_file($configPath) || $success;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Install LANtern</title>
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body class="dw-shell">
    <main class="dw-content">
        <h1>Install LANtern</h1>

        <?php if ($installed): ?>
            <div class="alert success">
                Installation completed. Remove install.php from the web server before using the site.
            </div>
            <p><a href="login.php" class="dw-btn dw-btn-primary">Go to login</a></p>
        <?php else: ?>
            <?php foreach ($errors as $error): ?>
                <div class="alert error"><?= e($error); ?></div>
            <?php endforeach; ?>

            <p>Enter the database and first administrator details.</p>

            <form method="post" class="dw-form">
                <input type="hidden" name="csrf" value="<?= e($_SESSION['install_csrf']); ?>">

                <h2>Database</h2>
                <label for="db_host">Database host</label>
                <input id="db_host" name="db_host" value="<?= e($form['db_host']); ?>" required>

                <label for="db_name">Database name</label>
                <input id="db_name" name="db_name" value="<?= e($form['db_name']); ?>" required>

                <label for="db_user">Database user</label>
                <input id="db_user" name="db_user" value="<?= e($form['db_user']); ?>" required>

                <label for="db_password">Database password</label>
                <input id="db_password" type="password" name="db_password" required>

                <h2>Site administrator</h2>
                <label for="site_name">Site name</label>
                <input id="site_name" name="site_name" value="<?= e($form['site_name']); ?>" required>

                <label for="admin_username">Admin username</label>
                <input id="admin_username" name="admin_username" value="<?= e($form['admin_username']); ?>" required>

                <label for="admin_password">Admin password</label>
                <input id="admin_password" type="password" name="admin_password" minlength="12" required>

                <label for="admin_password_confirm">Confirm admin password</label>
                <input id="admin_password_confirm" type="password" name="admin_password_confirm" minlength="12" required>

                <h2>Signup Protection</h2>
                <label for="turnstile_site_key">Cloudflare Turnstile site key</label>
                <input id="turnstile_site_key" name="turnstile_site_key" value="<?= e($form['turnstile_site_key']); ?>">

                <label for="turnstile_secret_key">Cloudflare Turnstile secret key</label>
                <input id="turnstile_secret_key" type="password" name="turnstile_secret_key" value="<?= e($form['turnstile_secret_key']); ?>">

                <button type="submit" class="dw-btn dw-btn-primary">Install</button>
            </form>
        <?php endif; ?>
    </main>
</body>
</html>